modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
  - finished
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - initramfs
  - bootloader
  - packages
  - shellprocess
  
branding: edbian
prompt-install: true
dont-chroot: false
quit-at-end: false

